# Generated by Django 5.1.3 on 2024-11-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_image', models.ImageField(upload_to='highlighted_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_App.uploadedimage')),
            ],
        ),
    ]
